# 넘파이 ( 패키지 이름수치연산)(선형대수)

## 리스트랑 넘파이랑 요소 곱셉 덧셈 뺄셈 등등 결과값 다르게 나오므로 이해잘하기

***구조*** 
 - arr==2
 - arr이라는 배열안에 저장되는 값

## 넘파이 : 배열 프로그래밍을 공부한다
 - 배열 프로그래밍 : 대규모 데이터를 빠르게 연산
 - 파이썬 리스트 : 속도 느림, 메모리 많이 차지
 - 넘파이(수치연산)(선형대수)(패키지) 배열 : 속고 빠름, 메모리 적게 차지, ***배열 요소 타입이 모두 동일***
 - 넘파이(수치연산)(선형대수)(패키지) 배열은 원소의 개수가 변경 안된다는 점이 리스트 배열과의 차이이다
 - 파이썬에서 배열을 사용하고 싶다면 넘파이를 이용해야한다
판다스
맷플랏립,플랏리,태블로,씨본

In [1]:
import numpy as np

아래 코드를 통해 리스트로부터 넘파이 배열이 만들어진다는것을 알수 있다

In [2]:
ar=np.array([1.1,2,3])
ar

array([1.1, 2. , 3. ])

위에 출력값은 [1,2,3]에서 1을 1.1로 바꿔주니 ***배열 요소 타입 모두 동일*** 조건으로 인해 결과값도 float값으로 출력됨

In [3]:
type(ar)

numpy.ndarray

In [4]:
myarr=np.arange(100000)     #0부터 99999까지
mylist=list(np.arange(100000))

# ##아래는 배열을 리스트로 바꿔주는 과정

In [5]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
list(np.arange(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [7]:
myarr=np.arange(100000)    
mylist=list(np.arange(100000))
list(np.arange(10))
myarr   # 값 출력됨
#mylist # 값 출력됨

array([    0,     1,     2, ..., 99997, 99998, 99999])

# 매직 명령어
 -  보통 %timeit 형태로 쓰임

In [8]:
%timeit myarr2=myarr*2
%timeit mylist2=[x*2 for x in mylist]

51 µs ± 602 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)
4.78 ms ± 141 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [9]:
myarr=np.arange(100000)    
mylist=list(np.arange(100000))

In [10]:
myarr

array([    0,     1,     2, ..., 99997, 99998, 99999])

In [11]:
myarr3=myarr*2

In [12]:
mylist3=[x*2 for x in mylist]

In [13]:
myarr3

array([     0,      2,      4, ..., 199994, 199996, 199998])

In [14]:
data = np.array([[1,-0,1.2],[0,-3,6]])
data

array([[ 1. ,  0. ,  1.2],
       [ 0. , -3. ,  6. ]])

In [15]:
data*2

array([[ 2. ,  0. ,  2.4],
       [ 0. , -6. , 12. ]])

In [16]:
data+data

array([[ 2. ,  0. ,  2.4],
       [ 0. , -6. , 12. ]])

In [17]:
list(data+data)

[array([2. , 0. , 2.4]), array([ 0., -6., 12.])]

# array를 리스트로 변환

## 아래는 넘파이 계산 결과값 방식

In [18]:
arr=np.array([1,2,3])
arr.ndim
arr.dtype 

dtype('int32')

In [19]:
arr

array([1, 2, 3])

In [20]:
arr*3

array([3, 6, 9])

In [21]:
arr*3+1

array([ 4,  7, 10])

In [22]:
arr*(3+1)

array([ 4,  8, 12])

## 아래는 리스트 계산 결과값 방식

In [23]:
[1,2,3]*3

[1, 2, 3, 1, 2, 3, 1, 2, 3]

 - 리스트와 넘파이는 서로 계산 방식이 틀리다

## 여기서 부터 다시 넘파이에서 계산 방식

- 아래는 각각 요소들이 조건에 각각 만족하는지에 대한 결과값

In [24]:
arr==2

array([False,  True, False])

In [25]:
arr>2

array([False, False,  True])

In [26]:
(arr==2)|(arr>2)

array([False,  True,  True])

In [27]:
arr.dtype

dtype('int32')

In [28]:
type(arr)

numpy.ndarray

## 모든 것을 0으로 출력 : zeros

In [29]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [30]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

## 모든 것을 1로 출력 : ones

In [31]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [32]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [33]:
np.ones(10)*2

array([2., 2., 2., 2., 2., 2., 2., 2., 2., 2.])

## 0과 1로 초기화해야 하는 경우가 빈번해서 zeros와 ones가 존재함

In [34]:
arr

array([1, 2, 3])

In [35]:
arr2=np.ones(3)
arr2

array([1., 1., 1.])

In [36]:
arr+arr2      # 요소끼리 더한 값이 출력

array([2., 3., 4.])

In [37]:
arr*arr2

array([1., 2., 3.])

## 타입 변환 : astype

In [38]:
arr1=arr.astype(np.float64)
arr1
arr1.dtype

dtype('float64')

In [39]:
arr2=arr1.astype(np.int32)
arr2

array([1, 2, 3])

In [40]:
arr1.astype(float)

array([1., 2., 3.])

## 특정값을 다른 값으로 변환
 - 리스트 처럼 범위나 특정 범위 값을 지정해서 변환가능
 - 꼭 무조건 범위를 지정해서 변환을 해야된다 그렇지 않으면 요소값이 없어진다

In [41]:
arr=np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
arr[5:8]=100
arr

array([  0,   1,   2,   3,   4, 100, 100, 100,   8,   9])

In [43]:
hund=arr[5:8]
hund

array([100, 100, 100])

In [44]:
arr[1]=999
arr

array([  0, 999,   2,   3,   4, 100, 100, 100,   8,   9])

## 이런 경우는 범위를 주지 않아서 요소가 없어지고 1만 나옴

In [45]:
arr=1                
arr

1

In [46]:
arr=np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
arr[:]=10
arr

array([10, 10, 10, 10, 10, 10, 10, 10, 10, 10])

## reshape : 행과 열에 대한 개수를 변경

In [48]:
np.arange(1,10).reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [49]:
arr2d=np.arange(1,10).reshape(3,3)
arr2d[0]

array([1, 2, 3])

### 앞에 행 뒤가 열

In [50]:
arr2d[1][0]             # 행과 열을 따로 참조 혹은

4

In [51]:
arr2d[1,0]             #행과 열을 한번에 지정해서 할 수 있음

4

In [52]:
#1 - 12까지 값으로 3행 4열 배열 생성
arr6=np.arange(1,13).reshape(3,4)
arr6[2][1]

10

# len

## 2차원 배열에서 len을 이용해서 행과 열을 구할수 있다

In [53]:
arr6
len(arr6) 

3

In [54]:
len(arr6[0])

4

## 3차원 배열

In [55]:
# 3차월 배열이며 (깊이(차원),행,열)
d= np.arange(1,25).reshape(2,3,4)      
d

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [56]:
len(d)       # 차원
len(d[0])    # 행
len(d[0][0]) # 열
d.ndim   # 몇 차원인지 물어보는 것
d.shape    # 2차원이면서 3행 4열인것

(2, 3, 4)

# sum : 합계

In [57]:
np.sum(d)
np.sum(d,axis=0)       #  차원(축)을 기준으로 합계

array([[14, 16, 18, 20],
       [22, 24, 26, 28],
       [30, 32, 34, 36]])

In [58]:
np.sum(d)
np.sum(d,axis=1)  #  행을 기준으로 합계

array([[15, 18, 21, 24],
       [51, 54, 57, 60]])

In [59]:
np.sum(d)
np.sum(d,axis=2) # 열을 기준으로 합계

array([[10, 26, 42],
       [58, 74, 90]])

In [60]:
arr = np.arange(1,13).reshape(3,4)

In [61]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [62]:
arr[:,2]

array([ 3,  7, 11])

In [63]:
arr[1,2:]
arr[1,2:4]

array([7, 8])

In [64]:
arr[2,:2]

array([ 9, 10])

# 이건 중요한 내용이니 잘 확인

## 불린참조

In [65]:
a=np.array([1,2,3])
b=np.array([True,False,True])

In [66]:
# True에 해당되는 자료를 참조
a
# b에 저장된 값이 True인 위치의 a배열 요소의 값을 참초
a[b]

array([1, 3])

## 불린 참조 응용 :  요소 추출

In [67]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [68]:
# arr배열에서 4의 배수만 추출
arr%4==0
arr[arr%4==0]

array([ 4,  8, 12])

In [69]:
a=np.arange(11,20)
a

array([11, 12, 13, 14, 15, 16, 17, 18, 19])

In [70]:
a[np.array([0,3,5])]

array([11, 14, 16])

### 아래와 같이 번호만 주면 번호수 만큼 추출이 가능

In [71]:
a[np.array([0,3,5,5,5,5,5,5])]

array([11, 14, 16, 16, 16, 16, 16, 16])

In [72]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [73]:
arr[[2,0,1],:]

array([[ 9, 10, 11, 12],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8]])

In [74]:
arr[:,[True,False,True,False]]

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11]])

In [75]:
brr=arr
brr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

# 값 치환

In [76]:
arr[1,0]=50
arr

array([[ 1,  2,  3,  4],
       [50,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [77]:
brr

array([[ 1,  2,  3,  4],
       [50,  6,  7,  8],
       [ 9, 10, 11, 12]])

# copy : 복사가 이루어 지는데 복사이전에 array에서 요소가 변하더라고
# 원본이 변경이되고 사본은 변경이 이루어 지지 않는다.

In [78]:
crr=arr.copy()
crr

array([[ 1,  2,  3,  4],
       [50,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [79]:
arr[2,0]=90
arr

array([[ 1,  2,  3,  4],
       [50,  6,  7,  8],
       [90, 10, 11, 12]])

In [80]:
crr

array([[ 1,  2,  3,  4],
       [50,  6,  7,  8],
       [ 9, 10, 11, 12]])

# 값 대입 및 추출

In [81]:
names=np.array(['kim','park','lee'])
data=np.array([[4,2],[0,2],[-1,2]])

In [82]:
names=="kim"
data[names=="kim"]
data[names=="kim",1]

array([2])

In [83]:
names
names !="park"
data[names !="park"]
data[names !="park",0]

array([ 4, -1])

# ~은 not의 의미

In [84]:
~(names=="kim")

array([False,  True,  True])

In [85]:
names
(names=="park")|(names=="lee")
data[(names=="park")|(names=="lee")]

array([[ 0,  2],
       [-1,  2]])

In [86]:
# 모든 데이터에 적용
data<0       

array([[False, False],
       [False, False],
       [ True, False]])

In [87]:
data[data<0]

array([-1])

In [88]:
# 음수에 관련된것을 0으로 치환
data[data<0]=0

In [89]:
data

array([[4, 2],
       [0, 2],
       [0, 2]])

In [90]:
 names

array(['kim', 'park', 'lee'], dtype='<U4')

In [91]:
data

array([[4, 2],
       [0, 2],
       [0, 2]])

In [92]:
data[names=="lee"]

array([[0, 2]])

In [93]:
data[names=="lee"]=999
data

array([[  4,   2],
       [  0,   2],
       [999, 999]])

In [94]:
arr=np.zeros((8,4))
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [95]:
arr[0,:]=0
arr[1,:]=1
arr[-1,:]=7
arr[0]
arr[1]
arr[-1]
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [7., 7., 7., 7.]])

# 브로드캐스팅

In [96]:
for i in range(8):
    arr[i]=i                    #arr은 2차원 i는 1차원구조라 연산이 되지 않아야하지만 브로드캐스팅을 통해
arr                             #[0,0,0,0] = 0 =>[0,0,0,0] =[0,0,0,0]
                               #  #[0,0,0,0] = 1 =>[1,1,1,1] =[1,1,1,1]

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])