import matplotlib as mp
import matplotlib.pylab as plt

y = [7, 6, 1]
x = np.arange(len(y))
xlabel = ['A', 'B', 'C']
plt.title("Bar Chart")
plt.bar(x, y)
plt.xticks(x, xlabel)
plt.yticks(sorted(y))
plt.xlabel("ABC")
plt.ylabel("낙차")
plt.show()

In [4]:
gravity=[7,4,2,0,0,6,0,7,0]
max_cnt=0

In [5]:
for i in range(len(gravity)-1): # i는 0부터 7까지
    cnt = 0
    for j in range(i+1,len(gravity)): # i+1 ~ 8 까지
        if gravity[i]>gravity[j]:       # 7 기준으로 본다면 낙차는 i는 7 j는 4
            cnt += 1
        if max_cnt<cnt:
            max_cnt=cnt

In [6]:
max_cnt

7

In [7]:
import numpy as np

In [8]:
arr=np.array([[0,1,0],[1,2,-2],[6,3,2],[-1,0,-1],[1,0,1]])
arr

array([[ 0,  1,  0],
       [ 1,  2, -2],
       [ 6,  3,  2],
       [-1,  0, -1],
       [ 1,  0,  1]])

# 전치행렬 : 행과 열이 바뀐것
# .T

In [9]:
arr.T

array([[ 0,  1,  6, -1,  1],
       [ 1,  2,  3,  0,  0],
       [ 0, -2,  2, -1,  1]])

# dot : 행렬의 곱셉

In [10]:
np.dot(arr,arr.T)

array([[ 1,  2,  3,  0,  0],
       [ 2,  9,  8,  1, -1],
       [ 3,  8, 49, -8,  8],
       [ 0,  1, -8,  2, -2],
       [ 0, -1,  8, -2,  2]])

# @ : 행렬의 곱셉

In [11]:
arr @ arr.T

array([[ 1,  2,  3,  0,  0],
       [ 2,  9,  8,  1, -1],
       [ 3,  8, 49, -8,  8],
       [ 0,  1, -8,  2, -2],
       [ 0, -1,  8, -2,  2]])

# 3행 2열, 2행 4열 행렬 생성 (난수 1 ` 10까지)

In [12]:
arr1=np.random.randint(1,11, size=(3,2))
arr1

array([[ 4,  4],
       [ 3, 10],
       [ 1,  8]])

In [13]:
arr2=np.random.randint(1,11, size=(2,4))
arr2

array([[7, 7, 1, 6],
       [6, 5, 8, 1]])

In [14]:
arr1 @ arr2

array([[52, 48, 36, 28],
       [81, 71, 83, 28],
       [55, 47, 65, 14]])

In [15]:
np.dot(arr1,arr2)

array([[52, 48, 36, 28],
       [81, 71, 83, 28],
       [55, 47, 65, 14]])

# 선형대수학

# 벡터 

In [16]:
"""
9월 6일 : 사과-5, 배-2,딸기-1
9월 7일 : 바난-3,딸기-2,배-1

'''
         사과(200)  배(100)  딸기(300)  바나나(500)
9월 6일   5             2     1           0
9월 7일   0             1     2           3

(5,2,1,0)     200       =    5*200 + 2*100 + 1*300 + 0*500 = 1500
(0,1,2,3)     100
           @  300
(2,3,1,0)     500


0 0 0 ...200 210 255...
0 255 210

"""

"\n9월 6일 : 사과-5, 배-2,딸기-1\n9월 7일 : 바난-3,딸기-2,배-1\n\n'''\n         사과(200)  배(100)  딸기(300)  바나나(500)\n9월 6일   5             2     1           0\n9월 7일   0             1     2           3\n\n(5,2,1,0)     200       =    5*200 + 2*100 + 1*300 + 0*500 = 1500\n(0,1,2,3)     100\n           @  300\n(2,3,1,0)     500\n\n\n0 0 0 ...200 210 255...\n0 255 210\n\n"

## mean : 평균 구하는 함수

In [17]:
samples=np.random.standard_normal(size=(4,4))
samples

array([[ 1.15217287, -0.53043153, -1.13121204, -1.46709833],
       [-0.70067438, -0.34677303,  0.79921217,  0.51554177],
       [ 1.69678921,  1.71059252, -0.37434294, -0.0699068 ],
       [ 0.04179366,  0.52409388, -0.47985796,  1.12290748]])

In [18]:
np.mean(samples)

0.15392540956778494

In [19]:
np.std(samples)

0.9319118497033088

In [20]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True,False,True,True,False])

In [21]:
(xarr*cond)

array([1.1, 0. , 1.3, 1.4, 0. ])

In [22]:
(yarr*~cond)

array([0. , 2.2, 0. , 0. , 2.5])

In [23]:
(xarr*cond)+(yarr*~cond)

array([1.1, 2.2, 1.3, 1.4, 2.5])

In [24]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True,False,True,True,False])

In [25]:
[(x if c else y) for x,y,c in zip(xarr,yarr,cond)]

[1.1, 2.2, 1.3, 1.4, 2.5]

#  where

In [26]:
# np.where(조건,참,거짓)
np.where(True, "참입니다","거짓입니다")

array('참입니다', dtype='<U5')

In [27]:
np.where(cond,xarr,yarr)

array([1.1, 2.2, 1.3, 1.4, 2.5])

In [28]:
arr=np.random.standard_normal((4,4))
arr

array([[-1.28219746,  0.25379736,  0.56592997,  0.01117917],
       [ 0.16261901, -0.14112839, -1.26208962, -0.38264866],
       [ 1.22590376,  1.26569088,  0.54569039, -0.98168992],
       [-0.8655921 ,  0.39239697, -0.92664304, -1.46852975]])

In [29]:
np.where(arr<0,0,arr)

array([[0.        , 0.25379736, 0.56592997, 0.01117917],
       [0.16261901, 0.        , 0.        , 0.        ],
       [1.22590376, 1.26569088, 0.54569039, 0.        ],
       [0.        , 0.39239697, 0.        , 0.        ]])

# 데이터프레임

In [30]:
import pandas as pd
import numpy as np

lst_A = {"제품":['milk','juice','bread','icecream'],
         "수량":[3,5,10,2],
         "제조일시":["2020-01-01 01:00","2019-12-30 15:01:00","2019-12-31 00:00:00", "2020-01-02 02:03:01"]
        }
df = pd.DataFrame(lst_A)
df
df['제조일시'] = pd.to_datetime(df["제조일시"])
df

제품  수량                제조일시
0      milk   3 2020-01-01 01:00:00
1     juice   5 2019-12-30 15:01:00
2     bread  10 2019-12-31 00:00:00
3  icecream   2 2020-01-02 02:03:01

In [31]:
df["초과여부"]=np.where(df["수량"]<5,"적정","초과")

In [32]:
df["수량"]<5

0     True
1    False
2    False
3     True
Name: 수량, dtype: bool

In [33]:
df

제품  수량                제조일시 초과여부
0      milk   3 2020-01-01 01:00:00   적정
1     juice   5 2019-12-30 15:01:00   초과
2     bread  10 2019-12-31 00:00:00   초과
3  icecream   2 2020-01-02 02:03:01   적정

In [34]:
df['제품종류']=np.where((df["제품"]=="juice")|(df["제품"]=="milk"),"음료","간식")

In [35]:
df

제품  수량                제조일시 초과여부 제품종류
0      milk   3 2020-01-01 01:00:00   적정   음료
1     juice   5 2019-12-30 15:01:00   초과   음료
2     bread  10 2019-12-31 00:00:00   초과   간식
3  icecream   2 2020-01-02 02:03:01   적정   간식

In [36]:
np.mean(arr)

-0.18045696361709448

In [37]:
arr.mean()

-0.18045696361709448

In [38]:
np.sum(arr)

-2.8873114178735118

In [39]:
arr.sum()

-2.8873114178735118

In [40]:
arr

array([[-1.28219746,  0.25379736,  0.56592997,  0.01117917],
       [ 0.16261901, -0.14112839, -1.26208962, -0.38264866],
       [ 1.22590376,  1.26569088,  0.54569039, -0.98168992],
       [-0.8655921 ,  0.39239697, -0.92664304, -1.46852975]])

# cumsum : 누적합

In [41]:
arr=np.arange(10,15)
arr.cumsum()

array([10, 21, 33, 46, 60])

In [42]:
arr=np.arange(10,16).reshape(3,2)
arr

array([[10, 11],
       [12, 13],
       [14, 15]])

In [43]:
arr.cumsum(axis=0)

array([[10, 11],
       [22, 24],
       [36, 39]])

In [44]:
arr.cumsum(axis=1)

array([[10, 21],
       [12, 25],
       [14, 29]])

In [45]:
a=[[10, 21],[12, 25],[14, 29]]
a
#sum(a) # 사용안됨

[[10, 21], [12, 25], [14, 29]]

In [46]:
a=[[10, 11],[12, 13],[14, 15]]
a
s=0
for i in a:
    for j in i:
        s+=j
s        

75

In [47]:
arr.sum()

75

In [48]:
a=[[10, 11],[12, 13],[14, 15]]
a
s=0
for i in a:
    for j in i:
        if j>=13:
            s+=j
s    

42

In [49]:
arr.sum()
arr>=13

array([[False, False],
       [False,  True],
       [ True,  True]])

In [50]:
arr.sum()
(arr>=13).sum()

3

In [51]:
arr.sum()
arr[arr>=13].sum()

42

In [52]:
arr

array([[10, 11],
       [12, 13],
       [14, 15]])

In [53]:
arr[1]
arr[0]
arr[2]

array([14, 15])

In [54]:
brr=arr[[1,0,2]]
brr

array([[12, 13],
       [10, 11],
       [14, 15]])

# 행과 열 오름차순

In [55]:
brr.sort(axis=0)
brr

array([[10, 11],
       [12, 13],
       [14, 15]])

In [56]:
brr.sort(axis=1)
brr

array([[10, 11],
       [12, 13],
       [14, 15]])

# unique : 데이터에서 중복값 제거

In [57]:
names=np.array(["Bob","Will","Joe","Bob","Will","Joe","Joe"])
np.unique(names)

array(['Bob', 'Joe', 'Will'], dtype='<U4')

In [58]:
ints=np.array([3,3,3,2,2,1,1,4,4,])
np.unique(ints)

array([1, 2, 3, 4])

In [59]:
set(names)              # set자료형 구조에도 중괄호가 사용됨

{'Bob', 'Joe', 'Will'}

# 난수생성

In [60]:
np.random.rand(3)

array([0.82185505, 0.02874265, 0.40769321])

# seed : 동기화(같은 난수가 나오게 됨)

In [61]:
np.random.seed(20230907)

In [62]:
np.random.rand(3)

array([0.64824332, 0.27289441, 0.9663242 ])

In [63]:
x=np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# shuffle : 데이터를 무작위로 섞는것

In [64]:
np.random.seed(20230907)

In [65]:
np.random.shuffle(x)
x

array([2, 5, 3, 4, 1, 0, 6, 8, 7, 9])

# choice : range,arange랑 같은 뜻

In [71]:
np.random.choice(5)

3

In [72]:
np.random.choice(5,3)

array([4, 2, 3])

# replace
 - replace=False는 replace하지 말라는 뜻
 - replace=True는 replace가 허용

In [68]:
np.random.choice(5,3,replace=False) # replace히자 말라는거 즉 중복된 값이 나오지 않는다

array([4, 3, 2])

- np.random.choice(5,10,replace=False)  # 이건 오류가 나옴
- np.random.choice(5, 10, replace=False)가 오류를 발생시키는 이유는 replace=False를 사용하면서 5개의 고유한 숫자를 10번 무작위로 선택하려고 하기 때문입니다. 그러나 0부터 4까지의 5개의 고유한 숫자만 사용 가능하기 때문에 중복되지 않는 10개의 숫자를 생성할 수 없습니다. 이렇게 코드를 실행하면 다음과 같은 ValueError가 발생할 것입니다:

In [69]:
np.random.choice(5,10,replace=True) 

array([2, 2, 1, 2, 2, 0, 1, 0, 2, 4])

# replace와 choice를 이용한 로또 문제

In [70]:
np.random.choice(45,6,replace=False)+1            # 범위는 1부터 44까지 

array([25, 30, 34,  3, 44, 24])

In [75]:
np.random.choice(5,3,replace=False)

array([1, 0, 4])